rabbit_mq:
  host: 127.0.0.1:5672
  user: "env:RABBITMQ_USERNAME"
  password: "env:RABBITMQ_PASSWORD"
  consumer_tag: hermes
  common:
    exchange: ctp.notifications.direct
    exchange_type: direct
  subs:
    - exchange: ctp.notifications.prices
      exchange_type: fanout
      queue: ctp.hermes.prices
    - exchange: ctp.notifications.orders
      exchange_type: fanout
      queue: ctp.hermes.orders
    - exchange: ctp.notifications.accounts
      exchange_type: fanout
      queue: ctp.hermes.accounts
    - exchange: ctp.notifications.deposits
      exchange_type: fanout
      queue: ctp.hermes.deposits

conn_number:
  conn_percentage: 58