# cache repository with flags: redis/boltdb
cache_storage_type: 'boltdb'

bolt_db:
  read_only: false
  timeout: 0
  file_path: 'bolt.db'

redis:
  dev_mode: false # when true, redis will be not used
  ping_interval: 60
  auth: "env:REDIS_PASSWORD"
  host: "0.0.0.0:6379"
  record_ttl: 60
  max_idle: 5 # Maximum number of idle connections in the pool.
  max_active: 0 # When zero, there is no limit on the number of connections in the pool.
